ARRAY FUNCTIONS

In [3]:
import numpy as np
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)

[[81. 52. 21.]
 [95. 77.  3.]
 [83. 58. 89.]]


In [4]:
#max/min/sum/prod

print(np.max(a1))
print(np.argmax(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

95.0
3
3.0
559.0
831647593216440.0


In [10]:
#0---> col and 1---> rows

print(np.max(a1, axis=1))
print(np.max(a1,axis=0))

[81. 95. 89.]
[95. 77. 89.]


In [11]:
#statistical operations

#medan/median/mode/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

54.44444444444444
46.0
22.78942791496439
519.3580246913581


In [14]:
#trigonometric functions
print(np.sin(a1))
print("-------------------------")
print(np.cos(a1))
print("-------------------------")
print(np.tan(a1))

[[ 0.83665564 -0.99920683 -0.67677196]
 [-0.99177885  0.51397846  0.90178835]
 [ 0.01770193 -0.26237485 -0.83177474]]
-------------------------
[[-0.54772926  0.03982088 -0.73619272]
 [-0.12796369 -0.85780309 -0.43217794]
 [ 0.99984331  0.96496603  0.5551133 ]]
-------------------------
[[-1.52749853e+00 -2.50925350e+01  9.19286404e-01]
 [ 7.75047091e+00 -5.99179998e-01 -2.08661353e+00]
 [ 1.77046993e-02 -2.71900612e-01 -1.49838734e+00]]


In [16]:
#dot peoduct

a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

print(a2)
print("-------------------------")
print(a3)
print("-------------------------")
result = np.dot(a2, a3)
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
-------------------------
[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [17]:
#LOG AND EXPONENETS

np.exp(a1)

array([[1.31881573e+09, 9.88903032e+42, 5.05239363e+31],
       [4.31123155e+15, 7.49841700e+33, 9.49611942e+19],
       [1.28516001e+19, 5.18470553e+21, 4.72783947e+18]])

In [25]:
#floor/ceil/lround

print(np.floor(np.random.random((2,3))))
print("  ")
print(np.round(np.random.random((2,3))))
print("")
print(np.ceil(np.random.random((2,3))))


[[0. 0. 0.]
 [0. 0. 0.]]
  
[[1. 1. 1.]
 [1. 1. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
g=np.eye(2)  #to make an identical matric=x


In [ ]:
z[1,1]=9    #it means basically the z[1,1] means that it will match row and column =1  and change the  value at that position