In [ ]:
import numpy as np

a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1
a2
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [1]:
#np.dim
# gives the dimensions of an array

a1.ndim
a2.ndim
a3.ndim

NameError: name 'a1' is not defined

In [13]:
#shape tells how many items are there in the array

a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [16]:
# size

a1.size
a2.size
a3.size

8

In [19]:
#itemsie
a1.itemsize
a2.itemsize
a3.itemsize

4

In [23]:
#dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


CHANGING DATATYPE

In [25]:
#astype
print(a3.astype)
print(a1.astype)
print(a2.astype)

<built-in method astype of numpy.ndarray object at 0x000001B9762B07B0>
<built-in method astype of numpy.ndarray object at 0x000001B975F3B390>
<built-in method astype of numpy.ndarray object at 0x000001B9762B1410>


ARRAY OPERATIONS

In [29]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print("================")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
#scalar operations

#arithmetic

print(a1*2)
print("-------------------------")
print(a1/2)
print("-------------------------")
print(a1%2)
print("-------------------------")
print(a1**2)


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
-------------------------
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
-------------------------
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
-------------------------
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [37]:
#relational

print(a1>5)
print("-------------------------")
print(a1==10)
print("-------------------------")
print(a1<15)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
-------------------------
[[False False False False]
 [False False False False]
 [False False  True False]]
-------------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [40]:
#vector  operations

# arithmetic

print(a1+a2)
print("-------------------------")
print(a1*a2)
print("-------------------------")
print(a1**a2)
print("-------------------------")
print(a1%a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
-------------------------
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
-------------------------
[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a='10'
b='20'   #remember the differcne
print(a+b)

1020


In [2]:
a=10
b=20
print("a+b")

a+b


In [ ]:
#convert one three line of print statement unto one line
print("go home")
print("dikshant is a  girl")


In [2]:
print("hello")

hello
